### ISSUE TITLE
'ft2build.h' file not found

### ISSUE THREAD

**Issue by itaysharir** [ashwamegh/Suckless-macbook#1]
I tired to install dmenu so i cloned the repo to ~/Suckless, and ran a "sudo make clean install" there. I got this output:

cd ~/Suckless/dmenu && sudo make clean install

rm -f dmenu stest drw.o dmenu.o stest.o util.o dmenu-4.9.tar.gz *.rej *.orig
dmenu build options:
CFLAGS   = -std=c99 -pedantic -Wall -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -DVERSION="4.9" -DXINERAMA
LDFLAGS  =
CC       = cc
cc -c -std=c99 -pedantic -Wall -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -DVERSION=\"4.9\" -DXINERAMA dmenu.c
In file included from dmenu.c:18:
/usr/X11R6/include/X11/Xft/Xft.h:39:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [dmenu.o] Error 1

**Comment by ashwamegh** [comment]
Hey, @itaysharir Did you try installing this library, if not follow this https://stackoverflow.com/questions/64059150/include-ft2build-h-in-project-on-linux to install it.

**Comment by itaysharir** [comment]
Thanks for the help but i solved it by changing some stuff in config.mk

I will send it so that more people can see this when I get home.

**Comment by ashwamegh** [comment]
Sure, comment it here to help others, Thanks @itaysharir 🙏
